# Travis CI config for automated Nikola blog deployments
language: python
cache: apt
sudo: false
addons:
  apt:
    packages:
      - ncftp

branches:
  only:
  - master

python:
  - 3.6

install:
  - pip install -U --upgrade-strategy=eager 'Nikola[extras]'
script:
  - cd www.pyss.org
  - nikola build

after_success:
  - cd output
  - find . -type f -exec curl -u $USERNAME:$PASSWORD --ftp-create-dirs -T {} ftp://$URL/{} \;


notifications:
    email:
        on_success: change
        on_failure: always
